<?php
/**
 * @file
 * homepage_banner.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function homepage_banner_field_default_fields() {
  $fields = array();

  // Exported field: 'node-banner-field_banner_image'.
  $fields['node-banner-field_banner_image'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_banner_image',
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'locked' => '0',
      'module' => 'image',
      'settings' => array(
        'default_image' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'image',
    ),
    'field_instance' => array(
      'bundle' => 'banner',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'image',
          'settings' => array(
            'image_link' => '',
            'image_style' => 'homepage_banner',
          ),
          'type' => 'image',
          'weight' => '0',
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_banner_image',
      'label' => 'תמונה',
      'required' => 1,
      'settings' => array(
        'alt_field' => 1,
        'default_image' => 0,
        'file_directory' => '',
        'file_extensions' => 'png gif jpg jpeg',
        'max_filesize' => '',
        'max_resolution' => '',
        'min_resolution' => '',
        'title_field' => 0,
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'image',
        'settings' => array(
          'preview_image_style' => 'homepage_banner',
          'progress_indicator' => 'throbber',
        ),
        'type' => 'image_image',
        'weight' => '0',
      ),
    ),
  );

  // Exported field: 'node-banner-field_banner_text'.
  $fields['node-banner-field_banner_text'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_banner_text',
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'locked' => '0',
      'module' => 'text',
      'settings' => array(),
      'translatable' => '0',
      'type' => 'text_long',
    ),
    'field_instance' => array(
      'bundle' => 'banner',
      'default_value' => array(
        0 => array(
          'value' => '<h2 style="font-size: 36px; font-weight: normal; letter-spacing: -1.9px; margin-bottom: 18px; padding-right: 15px; text-shadow: none !important; word-spacing: 2px;" dir="rtl"><span style="color: #333333;">אשכלנו את</span> הרשת בשבילך</h2><p style="font-size: 22px; line-height: 47px;" dir="rtl">אספנו קישורים למחקרים, מאמרים אקדמיים, פרסומים, דוחות, ניירות עבודה וכלי מחקר</p><p style="color: red; font-size: 20px; text-align: center; padding-top: 50px; line-height: 44px;" dir="rtl"><a class="form-submit" style="background: url(\'/sites/all/themes/e_scholar/images/homepage-slideshow-Action-b.png\') repeat scroll 0 0 transparent; color: white; display: inline-block; font-size: 13px; font-weight: bold; height: 39px; line-height: 37px; width: 159px;" target="_self">לורם איפסום דולור</a></p>',
          'format' => 'full_html',
        ),
      ),
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 1,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_banner_text',
      'label' => 'טקסט',
      'required' => 0,
      'settings' => array(
        'text_processing' => '1',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '5',
        ),
        'type' => 'text_textarea',
        'weight' => '2',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('טקסט');
  t('תמונה');

  return $fields;
}
